name: "Syntax validation"

on:
  pull_request:
      paths:
        - "**.json"
  push:
    branches:
      - "main"
    paths:
      - "**.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Validate JSON syntax"
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
