name: "Syntax validation"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Check JSON syntax"
        run: find . -type f -name '*.json' -exec sh -c 'cat "$1" | jq > /dev/null || echo "$1"' -- {} \; &> json.out

      - name: "Assert JSON syntax"
        run: |
          OUT=`cat json.out`
          [ -z "$OUT"] && exit 0 || (echo $OUT && exit 1)
